[[ISSUERS]]
address = "rKYKG2E6ZAo6urPY1N8YWrwwcNAyKUnTN3"
name = "TLXX"

[[TOKENS]]
issuer = "rKYKG2E6ZAo6urPY1N8YWrwwcNAyKUnTN3"
currency = "TLXX"
name = "TLXX"
desc = "TLXX"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https:google.com"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com"
type = "socialmedia"
